### ISSUE TITLE
Use more inclusive language

### ISSUE THREAD

**Issue by 5minpause** [cmer/nobspw#17]
Hi.
I am using nobspw in my projects. After updating to Rubocop 1.20.0 I received warnings for using a more inclusive language.
I used phrases like WHITELIST and BLACKLIST in my code, but now changed it. I believe it makes sense to use more inclusive language when talking and writing but also when writing code.

Now your wonderful gem has a config value named `blacklist`. I wanted to ask whether you are open to renaming that config to something along the lines of `denylist` or something similar?

If you are, I would gladly open a PR and make that change.

Thanks for your work.

**Comment by cmer** [comment]
Sure go ahead! Please add aliases to not break old code, however. I'm happy to change the default to what you suggested.
